services:
  # api:
  #   build: .
  #   container_name: smartplan-api-local
  #   profiles:
  #     - ['local-api']
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_URL: "Server=postgres;Port=1433;Database=smartplan-local;User Id=postgres;Password=postgres;"
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartplan-local
    volumes:
      - ./postgres-data:/var/lib/postgresql/data